### PR TITLE
Added deployment file for push and merge PR events

### PR DESCRIPTION
**Pull request by nitinja**
[Jira issue](https://jira.corp.adobe.com/browse/SITES-23543)

Successful run example: https://github.com/nitinja/aem-uix-examples/actions/runs/10606608061/job/29397668970
image

When commit is done in extensions that need not deployed, run will still succeed with no deployment.

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by AmyJZhao — APPROVED** [review]

**Comment by naydav** [comment]
@nitinja, could you show examples or explain how the deployment will work if the deployment of the extension in AppBuilder requires certain environment variables, like the Google API key?
Thank you.

**Comment by nitinja** [comment]
> @nitinja, could you show examples or explain how the deployment will work if the deployment of the extension in AppBuilder requires certain environment variables, like the [Google API key](https://github.com/adobe/aem-uix-examples/blob/main/address-autocomplete/src/aem-cf-editor-1/web-src/src/web-config.js#L6)? Since some extensions (at the moment) can only be deployed manually (or something like `merge` option during deployment for .env)
> 
> Thank you.

Right now, we are only able to auto-deploy apps that can be deployed using simply `aio app deploy` command. For this command to succeed, we need certain variables in `.env` file in project directory. Those variables are auto populated when you run `aio app use project-config.json` command. If the app requires additional environment variables, we can simply add those variables as environment variables in GitHub settings and build should run (although I have not tried `address-autocomplete` extension, since I do not have this key. If you provide this key, I can try). As of now, I have not added merge option, but it's possible to do it.

**Comment by nitinja** [comment]
For future reference: This is a generic build system that first detects all changed directories and individually and then runs build command in each of those directories after creating `.env` file according to the secret stored in GitHub with the key as directory name.

**Comment by nitinja** [comment]
cc @slitviachenko for reviewing retrospectively.

**Pull request merged**
